function newSample = reSampling(sample, numSamples)
% Re-samples the points generated by CHRR.

N  = sample.numSamples;
x0 = sample.points(:,randi(N));
acceptedCount = 0;
totalCount    = 0;
newSample.points = zeros(size(sample.points,1),numSamples);

% Burn-In
% Tiempo
% Fields to use

while acceptedCount < numSamples
    totalCount = totalCount + 1;
    x1 = sample.points(:,randi(N));
    ratio = myMVNPDF(sample,x0,x1) + calculateExpNormalRatio(sample,x0,x1);
    if ratio >= 0 || ratio >= log(unifrnd(0,1))
        acceptedCount = acceptedCount + 1;
        newSample.points(:,acceptedCount) = x1;
        x0 = x1;
        totalCount
        acceptedCount
    end
end


end